name: hack
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pysoundfile
  - editdistance
  - jupyter
  - pip:
      - openai-whisper
      - tensorboardX
